### ISSUE TITLE
Emacs Binding Keys and Configuration

### ISSUE THREAD

**Issue by louishuyng** [loishy/dotfiles#18]
## Description

Currently, I am moving to emacs for some experiments and exploring new tools so want to map it with my old binding keys for easy to use

## TODO
---
General
- [x] Navigation between the window
- [x] Split windows
- [x] Exit Emacs

--- 
Language
- [x] Go to definitation
- [x] Find Reference
- [x] Auto format when saving
- [x] Hover show implementation
- [ ] Renaming var or fun easily
- [ ] UI diagnostic error
- [x] go to next diagnostic error

---
Navigation
- [x] Search File
- [x] Folder Like Neotree consider using `treemacs`

---
Utilities
- [ ] Multiple cursors
- [x] Comment
